=== timjansen/jarfiller/jarfiller.com/schemas/page.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://tjansen.de/refPage" xmlns:tns="http://tjansen.de/refPage" elementFormDefault="qualified">

	<complexType name="popup">
		<complexContent>
			<extension base="tns:markup">
				<attribute name="name" type="string"/>
				<attribute name="id" type="ID" use="optional"/>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="shortcut">
		<attribute name="name" type="string"/>
		<attribute name="uri" type="string"/>
	</complexType>
	
	<complexType name="topic">
		<sequence>
			<element name="keyword" type="string" maxOccurs="unbounded"/>
			<element name="headline" type="string"/>
			<element name="abbreviation" type="string" minOccurs="0"/>
			<element name="description" type="tns:markup"/>
			<element name="relatedGuides" type="tns:markup" minOccurs="0"/>
			<element name="relatedReferences" type="tns:markup" minOccurs="0"/>
			<element name="homepage" type="tns:markup" minOccurs="0"/>
			<element name="wikipedia" type="tns:markup" minOccurs="0"/>
			<element name="specification" type="tns:markup" minOccurs="0"/>
			<element name="api" type="tns:markup" minOccurs="0"/>
			<element name="jsr" type="tns:markup" minOccurs="0"/>
		</sequence>
	</complexType>
	
    <element name="page">
    	<complexType>
   			<sequence>
   				<element name="path" type="string" />
   				<element name="root" minOccurs="0" type="string" />
   				
   				<element name="title" type="string" />
   				<element name="titleIntro" minOccurs="0" type="tns:markup" />
   				<element name="metaDescription" minOccurs="0" type="string" />
   				<element name="metaKeywords" minOccurs="0" type="string" />
				<element name="license" minOccurs="0" type="tns:licenseType"/>

   				<element name="styleSheet" minOccurs="0" type="string" />
   				<element name="embeddedStyle" minOccurs="0" type="string" />
   				
   				<element name="multipage" minOccurs="0"/>
   				
   				<element name="topicConfig" minOccurs="0">
   					<complexType>
   						<sequence>
   							<choice maxOccurs="unbounded" minOccurs="0">
   								<element name="topic" type="tns:topic"/>
   								<any namespace="http://tjansen.de/refPageInclude" processContents="skip"/>
   							</choice>
   						</sequence>
   					</complexType>
   				</element>
   				<element name="docConfig" minOccurs="0">
   				   	<complexType>
   						<sequence>
	   						<choice  minOccurs="0" maxOccurs="unbounded">
								<element name="popup" type="tns:popup"/>
								<any namespace="http://tjansen.de/refPageInclude" processContents="skip"/>
							</choice>
					</sequence>
   					</complexType>
   				</element>
   				<element name="javadocConfig" minOccurs="0">
   				   	<complexType>
   						<sequence>
   							<element name="baseURL" type="string"/>
   							<element name="defaultPackage" type="string" minOccurs="0"/>
   							<element name="defaultAnnotationPackage" type="string" minOccurs="0"/>
   							<element name="shortcuts" minOccurs="0">
   								<complexType>
   									<sequence>
				   						<choice minOccurs="0" maxOccurs="unbounded">
   											<element name="shortcut" type="tns:shortcut"/>
	   										<any namespace="http://tjansen.de/refPageInclude" processContents="skip"/>
   										</choice>
   									</sequence>
   								</complexType>
   							</element>
   						</sequence>
   					</complexType>
   				</element>
   				<choice>
	   				<element name="article">
	   					<complexType>
	   						<sequence>
	   							<element name="body">
	   								<complexType>
	   									<choice minOccurs="0" maxOccurs="unbounded">
				   							<element name="singleColumnSection" type="tns:singleColumnSection"/>
				   							<element name="exampleWithResult" type="tns:exampleSection" />
				   							<any namespace="http://tjansen.de/refPageInclude" processContents="skip"/>
				   						</choice>
   	   								</complexType>
	   							</element>
				   				<element name="sidebar">
				   					<complexType>
				   						<choice minOccurs="0" maxOccurs="unbounded">
				   							<element name="htmlBox">
				   								<complexType>
				   									<sequence>
				   										<element name="title" type="string" minOccurs="0"/>
				   										<element name="html"/>
				   									</sequence>
				   								</complexType>
				   							</element>
				   							<element name="box">
				   								<complexType>
				   									<sequence>
				   										<element name="title" type="string" minOccurs="0"/>
				   										<element name="subTitleLine" type="string" minOccurs="0"/>
				   										<element name="content" type="tns:markup"/>
				   									</sequence>
				   								</complexType>
				   							</element>
				   						</choice>
				   					</complexType>
				   				</element>
	   						</sequence>
	   					</complexType>
	   				</element>
	   				<element name="html">
	   					<complexType>
	   						<sequence>
	   							<any namespace="http://www.w3.org/1999/xhtml" minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
	   						</sequence>
	   					</complexType>
	   				</element>
   				</choice>
   			</sequence>
    	</complexType>
    	
		<unique name="anchorUniqueness">
   			<selector xpath="tns:article/tns:body/tns:singleColumnSection|tns:article/tns:body/tns:singleColumnSection/tns:collapsedSubSection|tns:article/tns:body/tns:singleColumnSection/tns:subSection"/>
   			<field    xpath="@anchor"/>
		</unique>
    </element>

    <complexType name="section">
    	<sequence>
    		<element name="head" type="string" />
    		<element name="intro" type="tns:markup" minOccurs="0" />
    	</sequence>
    	<attribute name="anchor" type="NMTOKEN" use="required"/>
    	<attribute name="multipage" type="boolean" use="optional"/>
    </complexType>

    <complexType name="subSection">
		<complexContent>
			<extension base="tns:subSectionContent">
		    	<attribute name="anchor" type="NMTOKEN" use="required"/>
		    	<attribute name="id" type="ID" use="optional"/>
			</extension>
		</complexContent>
    </complexType>

	<complexType name="subSectionContent">
		<sequence>
    		<element name="head" minOccurs="0" type="string" />
    		<element name="summary" minOccurs="0" type="string" />
    		<element name="more" type="tns:markup" minOccurs="0" />

    		<choice minOccurs="1" maxOccurs="unbounded">
    			<element name="code" type="tns:code" />
    			<element name="config" type="tns:markup" />
    			<element name="explanation" type="tns:markup" />
    			<element name="miniHeadline" type="tns:markup" />
    			<element name="list" type="tns:list" />
    			<element name="orderedList" type="tns:orderedList" />
    			<element name="table" type="tns:table" />
    			<element name="console" type="tns:markup" />
    			<element name="svgImage" type="tns:svgImage" />
    		</choice>
    	</sequence>
	</complexType>

	<complexType name="collapsedSubSection">
		<sequence>
			<element name="head" type="string" minOccurs="0"/>
			<element name="summary" type="string" />
			<element name="content" type="tns:subSectionContent"/>
		</sequence>
		<attribute name="anchor" type="NMTOKEN" use="required"/>
		<attribute name="id" type="ID" use="optional"/>
	</complexType>

    <complexType name="singleColumnSection">
		<complexContent>
			<extension base="tns:section">
				<sequence>  			
					<choice minOccurs="1" maxOccurs="unbounded" >
						<element name="subSection" type="tns:subSection"/>
						<element name="collapsedSubSection" type="tns:collapsedSubSection"/>
						<any namespace="http://tjansen.de/refPageInclude" processContents="skip"/>
					</choice>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="exampleSection">
		<complexContent>
			<extension base="tns:section">
				<choice minOccurs="0"
						maxOccurs="unbounded">
					<element name="explanation"
						type="tns:markup" />
					<element name="example">
						<complexType>
							<sequence>
								<element
									name="code" type="tns:code" />
								<element
									name="result">
									<complexType>
										<choice>
											<element
												name="code" type="tns:code" />
											<element
												name="image">
												<complexType>
													<attribute
														name="src" type="string" />
												</complexType>
											</element>
										</choice>
									</complexType>
								</element>
								<element
									name="source" type="string" minOccurs="0" />
								<element
									name="tryOut" type="string" minOccurs="0" />
							</sequence>
						</complexType>
					</element>
				</choice>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="code">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="line" type="tns:markup"/>
			<element name="emptyLine"><complexType></complexType></element> 															
		</choice>
	</complexType>

	<complexType name="list">
 		<annotation>
 			<documentation>Adds a list of bullet points</documentation>
 		</annotation>
		<sequence>
			<element name="li" minOccurs="1" maxOccurs="unbounded">
				<complexType mixed="true">
					<complexContent>
						<extension base="tns:markup">
							<choice  minOccurs="0" maxOccurs="unbounded">
								<element name="list" type="tns:list"/>
								<element name="orderedList" type="tns:list"/>
							</choice>
						</extension>
					</complexContent>
				</complexType>
			</element>
		</sequence>
 	</complexType>	

	<complexType name="orderedList">
		<annotation>
			<documentation>Adds a list of ordered points</documentation>
		</annotation>
		<sequence>
			<element name="li" minOccurs="1" maxOccurs="unbounded">
				<complexType mixed="true">
					<complexContent>
						<extension base="tns:markup">
							<choice  minOccurs="0" maxOccurs="unbounded">
								<element name="list" type="tns:list"/>
								<element name="orderedList" type="tns:list"/>
							</choice>
						</extension>
					</complexContent>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="table">
		<annotation>
			<documentation>Adds a table</documentation>
		</annotation>
		<sequence>
			<element name="head" minOccurs="0" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="cell" type="tns:markup" minOccurs="1"
							maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
			<element name="row" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="cell" type="tns:markup" minOccurs="1"
							maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
	
	<complexType name="svgImage">
		<annotation><documentation>Allows adding SVG with PNG fallback.</documentation></annotation>
		<attribute name="fileBase" type="string"/>
		<attribute name="width" type="int"/>
		<attribute name="height" type="int"/>
		<attribute name="alt" type="string"/>
   </complexType>

    <complexType name="markup" mixed="true">
    	<choice minOccurs="0" maxOccurs="unbounded">
    		<element name="em" type="tns:markup">
    			<annotation>
    				<documentation>Emphasizes the included text (e.g. make it bold).</documentation>
    			</annotation></element>
    		<element name="idf" type="tns:markup">
    			<annotation>
    				<documentation>Marks the given text as identifier (e.g. make it italic).</documentation>
    			</annotation></element>
       		<element name="javadoc">
                <annotation>
                	<documentation>Links to Javadocs. If @to is set, the link goes to the URL in the @to attribute. 
                	The URL may be either absolute (starting with http://) or relative (it will be appended to the Javadoc
                	base URL defined in the header). 
                	If there is no @to, it will try to get a link from the &lt;javadoc> configuration.</documentation>
                </annotation>
                <complexType>
	    			<complexContent>
	    				<extension base="tns:markup">
	    					<attribute name="to" type="string"/>
    						<attribute name="package" type="string"/>
    					</extension>
	    			</complexContent>
	    		</complexType>
    		</element>
    		<element name="doc">
                <annotation>
                	<documentation>Links to Popup documentation, which must be configured in docConfig.</documentation>
                </annotation>
                <complexType>
	    			<complexContent>
	    				<extension base="tns:markup">
	    					<attribute name="ref" type="string" use="optional"/>  <!-- type would be IDREF, but not possible with includes -->
	    				</extension>
	    			</complexContent>
    			</complexType>
    		</element>
    		<element name="tag">
                <annotation>
                	<documentation>Like doc, but puts angular brackets around the word. Allows attributes in the tag, like this
                			&lt;tag>name attr1="1" attr2="2"&lt;/tag></documentation>
                </annotation>
                <complexType>
	    			<complexContent>
	    				<extension base="tns:markup">
	    					<attribute name="ref" type="string" use="optional"/> <!-- type would be IDREF, but not possible with includes -->
	    					<attribute name="stand-alone" type="boolean" use="optional"/>
	    				</extension>
	    			</complexContent>
    			</complexType>
    		</element>
    		<element name="ctag" type="tns:markup">
    			<annotation>
    				<documentation>Closes a tag (puts closing angular brackets around it)</documentation>
    			</annotation></element>
    		<element name="topic" type="string">
    			<annotation>
    				<documentation>Marks an word or phrase as 'topic', which may open a popup explaining the term.</documentation>
    			</annotation></element>
       		<element name="link">
                <annotation>
                	<documentation>Renders the text as a link to the given URL @to, or links to the anchor @anchor.</documentation>
                </annotation>
                <complexType>
    			<complexContent>
    				<extension base="tns:markup">
    					<attribute name="to" type="string" use="optional"/>
    					<attribute name="anchor" type="NMTOKEN" use="optional"/>
    				</extension>
    			</complexContent>
    		</complexType>
    		</element>
    		<element name="cmt" type="tns:markup">
    			<annotation>
    				<documentation>declares a comment. Auto-indented. Does not need the '//'.</documentation>
    			</annotation></element>
    		<element name="plainCmt" type="tns:markup">
    			<annotation>
    				<documentation>declares a commend. No auto-indenting. Does not need the '//'.</documentation>
    			</annotation></element>
    		<element name="abstract" type="tns:markup">
    			<annotation>
    				<documentation>Marks an 'abstract' code segment that will not actually compile.</documentation>
    			</annotation></element>
    		<element name="strike" type="tns:markup">
    			<annotation>
    				<documentation>Strikes the text out.</documentation>
    			</annotation></element>
    		<element name="warn" type="tns:markup">
    			<annotation>
    				<documentation>Shows the text as a warning, e.g. in red.</documentation>
    			</annotation></element>
    		<element name="plainCode" type="tns:markup">
    			<annotation>
    				<documentation>Inserts a source code section.</documentation>
    			</annotation></element>
    		<element name="more">
    			<annotation>
    				<documentation>Creates a popup that contains the given additional text.</documentation>
    			</annotation>
    			<complexType>
    				<complexContent>
    					<extension base="tns:markup">
		    				<attribute name="id" type="ID" use="optional"/>
		    				<attribute name="ref" type="string" use="optional"/> <!-- type would be IDREF, but not possible with includes -->
    					</extension>
    				</complexContent>
    			</complexType>
    		</element>
    		<element name="annotated">
    			<annotation>
    				<documentation>Creates a popup that contains the given additional text.</documentation>
    			</annotation>
    			<complexType>
    				<choice>
    					<sequence/>
    					<sequence>
	    					<element name="title" type="tns:markup">
	    						<annotation>
	    							<documentation>The title of the tooltip.</documentation>
	    						</annotation></element>
	    					<element name="explanation" type="tns:markup" minOccurs="0"/>
    					</sequence>
    				</choice>
    				<attribute name="id" use="optional" type="ID"/>
    				<attribute name="ref" use="optional" type="string"/> <!-- type would be IDREF, but not possible with includes -->
    			</complexType>	
    		</element>
    		<element name="br">
    			<annotation>
    				<documentation>Adds a line break.</documentation>
    			</annotation>
    			<complexType></complexType>
    		</element>
    	</choice>
    </complexType>

    <simpleType name="licenseType">
    	<restriction base="string">
    		<enumeration value="cc-by-free-src"/>
    	</restriction>
    </simpleType>
    
    <element name="includables" >
    	<complexType>
        	<choice minOccurs="0" maxOccurs="unbounded">
        		<element name="topic" type="tns:topic"/>
				<element name="popup" type="tns:popup"/>
				<element name="shortcut" type="tns:shortcut"/>
				<element name="subSection" type="tns:subSection"/>
				<element name="collapsedSubSection" type="tns:collapsedSubSection"/>
				<element name="singleColumnSection" type="tns:singleColumnSection"/>
				<element name="exampleWithResult" type="tns:exampleSection" />
    			<any namespace="http://tjansen.de/refPageInclude" processContents="skip"/>
    		</choice>
    	</complexType>
    </element>
</schema>

=== timjansen/jarfiller/jarfiller.com/srcContent/javabasics/beans/javabasics-beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns="http://tjansen.de/refPage" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tjansen.de/refPage ../../../schemas/page.xsd ">

  <path>/javabasics/beans/</path>
  <title>Java Basics: Practical Guide to Beans and POJOs</title>
  <titleIntro></titleIntro>
   
  <license>cc-by-free-src</license>
   
  <multipage/>
   
  <javadocConfig>
	<baseURL>http://java.sun.com/javase/6/docs/api/</baseURL>
	<defaultPackage>java.lang</defaultPackage>
  </javadocConfig>

  <article><body>

	<singleColumnSection anchor="overview">
	  	<head>Overview</head>
		<subSection anchor="intro">
			<head>Intro</head>
			<explanation>
			</explanation>
		</subSection>
		<collapsedSubSection anchor="usecases">
			<head>Use cases</head>
			<summary>When to use assert?</summary>
			<content>
				<explanation>
- what is a bean today?
- what are POJOs?
- history of beans: beans are not GUI components anymore
- explain properties: getter/setter mechanisms
- explain bean reflection
- explain apache commons / beanutils
- dependency injection
- beans in spring and similar containers
- beans and multithreading (don't!)

Beans with annotations:
- EJBs (3.x)
- JPA
- JSF backing bean?

Older beans:
- EJBs (1.x/2.x)
- Swing GUI beans
				</explanation>
			</content>
		</collapsedSubSection>
		<subSection anchor="requirements">
			<head>Requirements</head>
			<explanation>Java supports the <idf>assert</idf> statement <em>since version 1.4</em> (in other words, practically forever).</explanation>
		</subSection>		
	</singleColumnSection>
		
  </body>
  <sidebar>
  	  	<box>
  		<title>Useful Links</title>
  		<content>
  		</content>
  	</box>
  </sidebar>
  </article>
</page>

=== timjansen/jarfiller/jarfiller.com/srcContent/shared/webxmldocs-2.5.inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includables xmlns="http://tjansen.de/refPage" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:inc="http://tjansen.de/refPageInclude"
	xsi:schemaLocation="http://tjansen.de/refPage ../../schemas/page.xsd ">
	
	<popup name="version">Declares the version of the Servlet Specification the descriptor uses, e.g. "2.4", "2.5" or
	"3.0". Newer versions are backward compatible, so "2.2" will work in 3.0 containers as well. Required.</popup>

	<popup id="doc-filter-mapping-url-pattern">Defines the URLs that the filter will respond to. A complete path, or
	"/path/*", "*.extension" or "/". Repeat to define several alternative patterns. Optional, more than one allowed. At least one 
	<idf>&lt;servlet-name></idf> or <idf>&lt;url-pattern></idf> must be present.</popup>
	<popup id="doc-filter-mapping-servlet-name">The name of a servlet to be filtered. Must match the <idf>&lt;servlet-name></idf>
	set in the <idf>&lt;servlet></idf> declaration. Use the special name "*" to match all requests. Repeat it to define several 
	alternative patterns. 
	Optional, more than one allowed. At least one <idf>&lt;servlet-name></idf> or <idf>&lt;url-pattern></idf> must be present.</popup>
	
	<popup id="doc-servlet-mapping-url-pattern">Defines the URLs that the servlet will invoked for. A complete path, or
	"/path/*", "*.extension" or "/". Repeat to define several alternative patterns. Required, more than one allowed.</popup>

    <inc:includeContent file="../srcContent/shared/webxmldocs-common.inc.xml"/>	
</includables>

=== timjansen/jarfiller/jarfiller.com/srcContent/reference/webxml/reference-webxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns="http://tjansen.de/refPage" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:inc="http://tjansen.de/refPageInclude" xsi:schemaLocation="http://tjansen.de/refPage ../../../schemas/page.xsd ">

  <path>/reference/webxml/</path>
  <title>Web.xml for Servlet 3.0 Reference</title>
  
  <titleIntro>Reference for the web.xml deployment descriptor and WAR files, according to the servlet specification 3.0 (Java EE 6).</titleIntro>
  
  <license>cc-by-free-src</license>

  <multipage/>

  <docConfig>
	<inc:includeContent file="../srcContent/shared/webxmldocs-2.4plus.inc.xml"/>
  </docConfig> 
  
  <javadocConfig>
	<baseURL>http://java.sun.com/javaee/5/docs/api/</baseURL>
	<defaultPackage>javax.servlet</defaultPackage>
  </javadocConfig>
  
  <article><body>

	<singleColumnSection anchor="skeletons">
	  	<head>Skeletons</head>
		<subSection anchor="skeletons1">
			<head>Skeleton</head>
			<explanation>
			This is the smallest possible <idf>web.xml</idf>. The <em><doc>version</doc> attribute must be adjusted</em> to match a
			version supported by your container
			<more>The servlet specification requires a web container to support older servlet versions. So "2.4" or "2.5" will still work in
			3.0, but you can't use newer servlet features.</more>.
			</explanation>
			<config><tag>web-app <doc>xmlns</doc>="http://java.sun.com/xml/ns/j2ee" <doc>version</doc>="<em>3.0</em>"</tag>
    <cmt>Put declarations here</cmt>
<ctag/></config>
			<explanation>Inside the <tag>web-app</tag> element, the <em>declarations can have any order</em>. In elements containing text,
<em>surrounding whitespace will be removed</em>.</explanation>

			<explanation>For editing with an XML-aware editor it is often better to declare the schema as well. Find complete snippets for
version 3.0 next.</explanation>
		</subSection>

		<collapsedSubSection anchor="skeletons30">
			<head>Skeleton for 3.0</head>
			<summary>Complete Web.xml Skeleton with Schema Declaration for Servlet 3.0</summary>
			<content>
				<config>&lt;?xml version="1.0" encoding="UTF-8"?>
<tag>web-app <doc>xmlns</doc>="http://java.sun.com/xml/ns/j2ee"
         <doc>xmlns:xsi</doc>="http://www.w3.org/2001/XMLSchema-instance"
         <doc>xsi:schemaLocation</doc>="http://java.sun.com/xml/ns/j2ee
                             http://java.sun.com/xml/ns/j2ee/web-app_3_0.xsd"
         <doc>version</doc>="3.0"</tag>

  <cmt>Put declarations here</cmt>

<ctag/></config>
			</content>
		</collapsedSubSection>
	</singleColumnSection>
	
	
	
	
	<singleColumnSection anchor="elements">
		<head>Elements</head>
	
		<subSection anchor="descriptions">
			<head>Descriptions</head>
			<config>
TODO: Copy some parts from web.xml 2.x...
TODO: Remove all JAX-RPC references from 2.x


New Elements in 3.0:			
filter/async-supported

servlet/async-supported

servlet/multipart-config

session-config/cookie-config
session-config/tracking-mode

security-constraint/web-resource-collection/http-method-omission

env-entry/mapped-name
env-entry/injection-target
env-entry/lookup-name

ejb-ref/mapped-name
ejb-ref/injection-target
ejb-ref/lookup-name

service-ref/mapped-name
service-ref/injection-target
service-ref/lookup-name

resource-ref/mapped-name
resource-ref/injection-target
resource-ref/lookup-name

resource-env-ref/mapped-name
resource-env-ref/injection-target
resource-env-ref/lookup-name

message-destination-ref/mapped-name
message-destination-ref/injection-target
message-destination-ref/lookup-name

persistence-context-ref

persistence-unit-ref

data-source

post-construct

pre-destroy

<!-- 

    <tag>handler-chains</tag>                                   <cmt>optional, only for JAX-WS</cmt>
        <tag>handler-chain</tag>                                <cmt>one per handlerchain</cmt>
            <cmt><em>choice</em>: only one of the next 3 restrictions is possible (or none)</cmt>
            <tag>service-name-pattern xmlns:jf="http://jarfiller.com/ws"</tag> <cmt>optional</cmt>
                jf:JF*                                          <cmt>filter service name</cmt>
            <ctag/>
            <tag>port-name-pattern</tag>                        <cmt>optional</cmt>
                jf:JFPort*                                      <cmt>filter port name</cmt>
            <ctag/>                                          
            <tag>protocol-bindings</tag>                        <cmt>optional</cmt>
                ##SOAP11_HTTP ##SOAP12_HTTP                     <cmt>filter protocol</cmt>
            <ctag/>
       
            <tag>handler</tag>                                  <cmt>one per handler</cmt>
                <tag>description</tag>My Handler<ctag/>                 <cmt>optional</cmt>
                <tag ref="doc-handler-display-name">display-name</tag>handler1<ctag/>                  <cmt>optional</cmt>
                <tag>handler-class</tag>com.jarfiller.example.WSHandler<ctag/>
                <tag>soap-role</tag><ctag/>                          <cmt>optional, one per role</cmt>
                <tag>port-name</tag><ctag/>                          <cmt>optional, one per port name</cmt>
            <ctag/>
       
        <ctag/>
    <ctag/>
			 -->
			</config>
		</subSection>
		
		
	</singleColumnSection>


  </body>
  <sidebar>
  	  	<box>
  		<title>Useful Links</title>
  		<content>
  			<link to="http://jcp.org/en/jsr/detail?id=315">Servlet 3.0 Specification / JSR</link><br/>
  			<link to="http://jcp.org/aboutJava/communityprocess/mrel/jsr154/index.html">Servlet 2.5 Specification / JSR</link><br/>
  			<br/>
  			<link to="http://java.sun.com/javaee/6/docs/api/">JEE 6 API</link><br/>
  		</content>
  	</box>
  </sidebar>
  </article>
</page>

=== timjansen/jarfiller/jarfiller.com/srcContent/shared/webxmldocs-2.4plus.inc.xml
<?xml version="1.0" encoding="UTF-8"?>
<includables xmlns="http://tjansen.de/refPage" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:inc="http://tjansen.de/refPageInclude"
	xsi:schemaLocation="http://tjansen.de/refPage ../../schemas/page.xsd ">
	
	<popup name="version">Declares the version of the Servlet Specification the descriptor uses, e.g. "2.4", "2.5" or
	"3.0". Newer versions are backward compatible, so "2.4" will work in 2.5 and 3.0 containers as well. Required.</popup>

	<popup id="doc-filter-mapping-url-pattern">Defines the URLs that the filter will respond to. A complete path, or
	"/path/*", "*.extension" or "/". Since Servlet version 2.5 you can repeat it to define several alternative patterns (in
	2.4 you need to repeat the whole <idf>&lt;filter-mapping></idf>). Optional, more than one allowed in 2.5. Either 
	<idf>&lt;servlet-name></idf> or <idf>&lt;url-pattern></idf> must be present.</popup>
	<popup id="doc-filter-mapping-servlet-name">The name of a servlet to be filtered. Must match the <idf>&lt;servlet-name></idf>
	set in the <idf>&lt;servlet></idf> declaration. Since Servlet version 2.5 you can repeat it to define several alternative patterns (in
	2.4 you need to repeat the whole <idf>&lt;filter-mapping></idf>), and also use the special name "*" to match all requests.
	Optional, more than one allowed in 2.5. Either <idf>&lt;servlet-name></idf> or <idf>&lt;url-pattern></idf> must be present.</popup>
	
	<popup id="doc-servlet-mapping-url-pattern">Defines the URLs that the servlet will invoked for. A complete path, or
	"/path/*", "*.extension" or "/". Since Servlet 2.5 you can repeat to define several patterns (in version 2.4 you
	have to repeat the whole <idf>&lt;servlet-mapping></idf>). Required, more than one allowed in 2.5.</popup>

    <inc:includeContent file="../srcContent/shared/webxmldocs-common.inc.xml"/>	
	
</includables>
